### PR TITLE
Update transaction.blade.php

### PR DESCRIPTION
**Pull request by eugenefvdm**
Fix date format

The date showed the month in the place of he minutes and seconds were missing.

### CODE REVIEW

**Comment by alecritson** [comment]
Thanks @eugenefvdm although I'm not sure we need to show seconds I think something like `2nd January 2024 03:30pm" should be sufficient. @glennjacobs ?

**Comment by glennjacobs** [comment]
> Thanks @eugenefvdm although I'm not sure we need to show seconds I think something like `2nd January 2024 03:30pm" should be sufficient. @glennjacobs ?

Seconds is unlikely to be useful, so yeah, let's remove.

**Comment by eugenefvdm** [comment]
I added minutes because if you're doing many transactions per minute you can use the seconds for troubleshooting.

But of course, I can change it to the below as per @alecritson 

```php
$today = now()->format("jS F Y h:ia");
echo $today;
22nd May 2024 01:42pm
```

**Review by alecritson — APPROVED** [review]

**Comment by alecritson** [comment]
> I added minutes because if you're doing many transactions per minute you can use the seconds for troubleshooting.
> 
> But of course, I can change it to the below as per @alecritson
> 
> ```
> $today = now()->format("jS F Y h:ia");
> echo $today;
> 22nd May 2024 01:42pm
> ```

Sure, although I don't think this is a concern for Lunar right now as we currently don't have a way to view all transactions in a single place. Might be something for the future

**Pull request merged**
