### PR TITLE
Add new badge count on sidebar : product, channels

### PR DESCRIPTION
**Pull request by lguichard**
I purpose to add new count badge on sidebar.

### CODE REVIEW

**Comment by glennjacobs** [comment]
Is this needed?

I think for things like Orders it makes sense, but not sure we need a constant reminder of how many products and channels we have. If we add lots of badges, it will distract from the more important ones.

@alecritson can I have your opinion please?

**Comment by alecritson** [comment]
I agree with @glennjacobs I'm open to them being added where it makes sense, otherwise it's just noise.

**Comment by glennjacobs** [comment]
Closing as I don't see a value in the additional badges.

**Comment by lguichard** [comment]
Ok, as you want. Maybe channel it's not necessary. The number of products in the catalog is not indicated anywhere. For example with my catalog team the leader like follow number of new products, draft products etc. 

I purpose variation on new commit : 


Capture d’écran 2023-12-20 à 16 25 08

**Pull request closed without merging**
