### PR TITLE
Fix - Update Stripe dependencies

### PR DESCRIPTION
**Pull request by lguichard**

### CODE REVIEW

**Comment by alecritson** [comment]
Thanks @lguichard This seems like quite the jump in versions, was there any upgrade guides that need to be considered if not already done?

**Comment by adevade** [comment]
But it has to be updated, right? It seems a lot of things has been deprecated and removed from the API since v7 from 2022.

Useful links:

[Migration Guide for v8](https://github.com/stripe/stripe-php/wiki/Migration-Guide-for-v8)
[Migration Guide for v9](https://github.com/stripe/stripe-php/wiki/Migration-guide-for-v9)
[Migration Guide for v10](https://github.com/stripe/stripe-php/wiki/Migration-guide-for-v10)
[Migration Guide for v11 (Skipped)](https://github.com/stripe/stripe-php/wiki/Migration-guide-for-v11)
[Migration Guide for v12](https://github.com/stripe/stripe-php/wiki/Migration-guide-for-v12)
[Migration Guide for v13](https://github.com/stripe/stripe-php/wiki/Migration-guide-for-v13)
[Release Notes for v14](https://github.com/stripe/stripe-php/blob/master/CHANGELOG.md#1400---2024-04-10)

**Comment by alecritson** [comment]
Yup it certainly needs to be on the latest version as long as anything that needs updating on the Stripe package is considered.

**Comment by lguichard** [comment]
I will update stripe package with new dependencies.

**Comment by alecritson** [comment]
@lguichard I've had a little look through the migration guides and I don't think there is too much we need to worry about, I've done one update to the `StripeManager` class but apart from that I think we're good.

**Comment by adevade** [comment]
@alecritson Why did you revert the typing?

**Comment by alecritson** [comment]
> @alecritson Why did you revert the typing?

It was already covered by a commit on 1.0 so actually created a conflict because this branch hadn't been updated. The typings are still there 😃

**Review by alecritson — APPROVED** [review]

**Pull request merged**
