### PR TITLE
Feat - Form Builder Improvements

### PR DESCRIPTION
**Pull request by adam-code-labx**
Reference to #480

### CODE REVIEW

**Comment by alecritson** [comment]
As @wychoong mentioned, this should really be it's own isolated PR as it's very difficult to see what's going on. It does feel it should be able to stand alone without knowledge of data table or brand changes...

**Comment by adam-code-labx** [comment]
Sure no problem I will base this on the channels form to show how this is working to refactor the existing forms.

**Comment by adam-code-labx** [comment]
@alecritson @wychoong 
I have rebased this branch to only show the form builder commits and just added an example refactor for Channels.
Note currently supports Text and Toggle I will add the other fields + create and fix existing tests once approved.

**Comment by adam-code-labx** [comment]
Another interesting one would be to refactor Taxes as this has multiple columns and blocks.
Let me know if you would like me to proceed with this example?

**Comment by adam-code-labx** [comment]
@alecritson just merged with the latest develop branch and fixed the issues with the channel test.
You can see how simple these form components are and much more developer friendly zero dependencies outside GC for this one.

Hope you will consider this to be merged over to develop.
Really saves a lot of time creating and modifying existing forms. Similar to the way you have created GetCandyTable TableRegistry and TableExtension I would like to continue with this to offer the same functionality which will give developers complete control when adding / modifying fields in a form schema.

**Comment by alecritson** [comment]
Thanks for taking the time on this @adam-code-labx 

We've been chatting over this kind of thing internally and we've realised we really want to limit what third party packages we bring into the eco system, especially when they will be providing core functionality like form building. I think if we was going to do something, we'd want it do it ourselves to have more control and not get into issues when updating to new versions.

Unfortunately, I'm going to close this PR as I don't think this is the direction we'll be taking, but thank you for the effort.

**Comment by adam-code-labx** [comment]
> Thanks for taking the time on this @adam-code-labx
> 
> We've been chatting over this kind of thing internally and we've realised we really want to limit what third party packages we bring into the eco system, especially when they will be providing core functionality like form building. I think if we was going to do something, we'd want it do it ourselves to have more control and not get into issues when updating to new versions.
> 
> Unfortunately, I'm going to close this PR as I don't think this is the direction we'll be taking, but thank you for the effort.

Well that does not make sense this has nothing to do with Filament forms and no third part dependencies so what’s the problem here @alecritson 🤷‍♂️

**Comment by glennjacobs** [comment]
@alecritson I think you've assumed Filament Forms here? It looks like Adam has introduced something specifically for GetCandy, perhaps taking influence from Filament?

This kind of goes in line with our plans for other bits, which I won't go into here as they're not public yet.

**Comment by alecritson** [comment]
Yeah there has obviously been some confusion here. Will re-open

**Comment by glennjacobs** [comment]
@alecritson we'll need to book some time to review this properly at some point soon.

**Comment by glennjacobs** [comment]
We still need to review this properly, but priorities have prevented it. Due to this and file conflicts, I have converted to Draft for the moment.

**Comment by glennjacobs** [comment]
Closing this, as it's not longer relevant with our plans to move to Filament v3.

**Comment by adam-code-labx** [comment]
No problem @glennjacobs makes perfect sense and great move with Filament v3
I am also adjusting my plans around the v3 TALL Stack 💪

**Pull request closed without merging**
