### PR TITLE
fix price breaks not storing in correct currency factor

### PR DESCRIPTION
**Pull request by wychoong**
also added `->required()` to shipping method

### CODE REVIEW

**Comment by alecritson** [comment]
Thanks @wychoong Should we also be considering the Min. Spend field as well?

**Comment by wychoong** [comment]
> Thanks @wychoong Should we also be considering the Min. Spend field as well?

Min. Spend field is actually min_quantity field on the table, and currently it is hardcoded to multiply 100.
do you want me to update it to use currency factor too?

**Comment by alecritson** [comment]
I think so, since the shipping addon uses this as a price check 🤔

**Comment by wychoong** [comment]
> I think so, since the shipping addon uses this as a price check 🤔

I have updated both to use the currency factor. Also fixed my previous change which uses default currency. now it uses the currency selected at the repeater 😶‍🌫️ 
image

**Review by glennjacobs — APPROVED** [review]

**Pull request merged**
