### PR TITLE
Configurable default measurement units

### PR DESCRIPTION
**Pull request by netzknecht**
- remove partly wrong default measurement units from database ('weight' and 'volume' unit isn't 'mm')
 - allow configuration of default measurement units in config file `shipping.php` with `'default' => true` key/value pair
 - refactoring attribute getter methods to attribute casting accessor with correct default values

### CODE REVIEW

**Comment by netzknecht** [comment]
Because this pull request is a fix and an enhancment, it could be better to merge it into main branch?

**Comment by alecritson** [comment]
Do you see any changes this would cause that would need explaining in the upgrade guide?

**Comment by glennjacobs** [comment]
@netzknecht could you retarget to `0.8` branch please?

**Comment by glennjacobs** [comment]
This PR seems to have lots of updates not associated to the functionality specified. Closing, but feel free to reopen if you can make a PR that is focused on a single issue.

**Pull request closed without merging**
