### PR TITLE
Pricing manager pipelines

### PR DESCRIPTION
**Pull request by wychoong**
add pipelines for pricing manager to allow modifying

- [x] Documentation updates
- [x] Automated tests
- [x] Changelog entries (core and hub)

### CODE REVIEW

**Comment by alecritson** [comment]
@wychoong Converting this to draft and suggest this goes in `0.4` now as we're going to be releasing `0.3` soon.

**Comment by wychoong** [comment]
> @wychoong Converting this to draft and suggest this goes in `0.4` now as we're going to be releasing `0.3` soon.

how can i change the base into `main` without showing 140+ of files changes lol?

**Comment by alecritson** [comment]
I think if you bring your branch up to date with the one you want to target, GitHub should hopefully be able to figure it out

**Comment by wychoong** [comment]
ok, maybe is should squash it when merging `main` into it 😅

**Review by glennjacobs — APPROVED** [review]

**Pull request merged**
