### PR TITLE
Add base `LunarException` and other updates to exceptions

### PR DESCRIPTION
**Pull request by adevade**
Added a base `LunarException` class (that extends the standard `Exception` class) adding more flexibility for users.
All Lunar exceptions now extend from that instead.

---

Added types for method arguments where missing (base Cart and Fieldtype exceptions).

---

Added a missing translation in the base `CartException` class.

---

Formatted according to most empty Laravel framework exceptions (ex [MathException.php](https://github.com/laravel/framework/blob/e574ffa03436a85d0aefccca9d8127746b3032aa/src/Illuminate/Support/Exceptions/MathException.php#L7-L10), [DeadlockException.php](https://github.com/laravel/framework/blob/e574ffa03436a85d0aefccca9d8127746b3032aa/src/Illuminate/Database/DeadlockException.php#L7-L10))

--- 

Feel free to request or push changes 👍

### CODE REVIEW

**Comment by adevade** [comment]
This is ready for review. Should it still target the 0.7 branch?

**Comment by glennjacobs** [comment]
> This is ready for review. Should it still target the 0.7 branch?

As this isn't a bug fix, it should really target `0.8` please.

**Comment by adevade** [comment]
Switched to `0.8` branch and pulled in latest changes 👍

**Comment by adevade** [comment]
Fixed formatting conflicts

**Comment by adevade** [comment]
PHP 8.3 added more granular exceptions and errors in a similar fashion: [php.watch/versions/8.3/datetime-exceptions](https://php.watch/versions/8.3/datetime-exceptions#:~:text=Hierarchy%20of%20the%20Date/Time%20Exception%20classes)

**Comment by adevade** [comment]
Should I retarget this to `1.x` instead and fix potential merge conflicts? Just want to help out! 😊 I know that you guys have a lot on your plates with the alpha releases. Keep up the good work! 👍

**Comment by glennjacobs** [comment]
> Should I retarget this to `1.x` instead and fix potential merge conflicts? Just want to help out! 😊 I know that you guys have a lot on your plates with the alpha releases. Keep up the good work! 👍

No it's fine. We've been a little off the radar as we've been "dog flooding" Lunar 1.x with our projects to ensure we're happy with it. We intend to merge all the 0.8 PRs soon (assuming they're good) and then merge that back into 1.x.

**Review by glennjacobs — APPROVED** [review]

**Comment by glennjacobs** [comment]
Thanks @adevade this is a good helpful addition.

**Pull request merged**
