### PR TITLE
Add option to automatically apply BuyXGetY discount rewards

### LINKED ISSUE #876: Discount BuyXGetY automatically add
It would be great if there was the option to add Y items automatically to the cart when you have matching X items in your cart. This is really useful for say a free ebook alongside a paperback purchase.

I'd be happy to work on this if it was something you'd consider acceptable?

### PR DESCRIPTION
**Pull request by ryanmitchell**
This PR is a first pass at adding an option to automatically add BuyXGetY discount rewards.

It adds a toggle to the discount create/edit screen to automatically add.

When selected we work out if any rewards are available that haven't yet been added to the cart and if we so we add them. Along the way we keep track of how many we added, so we can decrement/increment if cart values are changed, and if necessary remove the item from the cart when it no longer is eligible.

Devs can check for whether an item was added by discount by checking the meta->added_by_discount array values ... if the sum is the same as the cart line quantity then it was added by a discount and can be displayed differently (if required).

Closes #876

### CODE REVIEW

**Review by glennjacobs — DISMISSED** [review]

**Comment by glennjacobs** [comment]
@alecritson can you fix the merge conflict and merge?

**Comment by alecritson** [comment]
@ryanmitchell I had a go at resolving the PR conflicts, if you're happy it's all good then we can get this merged!

**Comment by alecritson** [comment]
@ryanmitchell Looks like something has cropped up from when `$affectedLines` was added in another PR. Do you think this would be an easy fix?

**Comment by ryanmitchell** [comment]
I think this one needs some work to be brought into link with discount breakdowns - can we leave this for the next release?

**Comment by glennjacobs** [comment]
> I think this one needs some work to be brought into line with discount breakdowns - can we leave this for the next release?

That would be 0.3 now, when we look to update for L10

**Comment by ryanmitchell** [comment]
Thats fine, it just needs refactored a bit and I dont want to rush it and introduce an error

**Comment by ryanmitchell** [comment]
@alecritson when you get a chance could I get a 2nd pair of eyes on this. I've update it to work but I'm not super thrilled about some of how it is working - particularly having to duplicate the pipeline functionality cart line actions. No rush, but would be good to hear if you can think of a better way to make it work.

**Comment by Rkallenkoot** [comment]
Currently testing and encountering `DivisionByZeroError` with a 2+1, quantity in Cart `7` .

**Comment by Rkallenkoot** [comment]
Opened a PR for part of the issue: #1235, the PR also fixed the case of 2+1 with linesQuantity 7, maxReward 10. While it doesn't include the exact testcase, it does include a test for cases where 2+1 will end up as a float. 

Perhaps when testing the AutomaticReward, we might want to add 2+1 with linesQuantity 7, maxReward 10 to check for the DivisionByZero again.

**Comment by glennjacobs** [comment]
@ryanmitchell do you think this PR is likely to be continued?

**Comment by ryanmitchell** [comment]
Yeah I'll try and get it updated this week.

**Pull request closed without merging**
