### PR TITLE
Feature - Add search filtering/extending resources

### PR DESCRIPTION
**Pull request by alecritson**

### CODE REVIEW

**Comment by alecritson** [comment]
I think this will need #1454 to be merged first to use the plugin.

**Comment by glennjacobs** [comment]
Looks good.

**Comment by glennjacobs** [comment]
@alecritson can this be updated now that the other PR has been merged?

**Comment by glennjacobs** [comment]
This is quite out of date now and I don't agree with having a separate method to specifically extend table filters, as we can already extend the table. So closing.

**Pull request closed without merging**
