### PR TITLE
fix: saving product url with core model instead of extended model

### PR DESCRIPTION
**Pull request by wychoong**
refer to https://discord.com/channels/497326121441034240/712995078884294656/1034588048131891262

### CODE REVIEW

**Comment by wychoong** [comment]
there are other places used `get_class` but I'm not sure should it be updated as well.
maybe @adam-code-labx can advice https://github.com/lunarphp/lunar/search?p=4&q=get_class%28&type=code

**Comment by armezit** [comment]
This PR fixes #767

**Comment by alecritson** [comment]
Thanks @wychoong do we also need to consider other area's where we use polymorphic relations 🤔

**Comment by armezit** [comment]
@wychoong @alecritson The `UpdatePrices` action must be changed too:
https://github.com/lunarphp/lunar/blob/a27ce4b061b949773fa374dbeedcf0d18f9a4fcd/packages/admin/src/Actions/Pricing/UpdatePrices.php#L63

**Comment by wychoong** [comment]
> Thanks @wychoong do we also need to consider other area's where we use polymorphic relations 🤔

ideally yes, but I unable to test all

**Comment by wychoong** [comment]
replace with #807

**Pull request closed without merging**
