### PR TITLE
Hotfix [0.2] discount priority 

### PR DESCRIPTION
**Pull request by wychoong**
discount should apply from high to low 

`priority => 1: Low, 5: Medium, 10: High`

### CODE REVIEW

**Comment by alecritson** [comment]
Has something happened by changing the order that's caused the tests to fail? Just wondering if there is a deeper issue.

**Comment by wychoong** [comment]
> Has something happened by changing the order that's caused the tests to fail? Just wondering if there is a deeper issue.

the ordering definitely gonna impact the outcome of the calculation, but before fixing the test, we need to establish whether the current order is wrong

**Comment by alecritson** [comment]
> > Has something happened by changing the order that's caused the tests to fail? Just wondering if there is a deeper issue.
> 
> the ordering definitely gonna impact the outcome of the calculation, but before fixing the test, we need to establish whether the current order is wrong

Yeah I think we do want to order High > Medium > Low

**Comment by wychoong** [comment]
> > > Has something happened by changing the order that's caused the tests to fail? Just wondering if there is a deeper issue.
> > 
> > 
> > the ordering definitely gonna impact the outcome of the calculation, but before fixing the test, we need to establish whether the current order is wrong
> 
> Yeah I think we do want to order High > Medium > Low

should be ready now, added `orderBy('id')` for when discount is same priority

**Review by glennjacobs — APPROVED** [review]

**Pull request merged**
