### PR TITLE
doc: add remark for custom model definition

### PR DESCRIPTION
**Pull request by wychoong**
when a Lunar model is extended/replaced, the media definition config should be updated. Or standard definition will be used

p/s: not sure should the media definition to change to string alias or internally auto resolve to lunar model fqcn

### CODE REVIEW

**Comment by alecritson** [comment]
I think it would be more beneficial if the media definition worked with extended models. My thinking is that you should be able to just remove model extending in one place without having to then update a bunch of config etc in order to remove it if that makes sense.

**Comment by wychoong** [comment]
> I think it would be more beneficial if the media definition worked with extended models. My thinking is that you should be able to just remove model extending in one place without having to then update a bunch of config etc in order to remove it if that makes sense.

Totally agree. In config you prefer alias or fqcn?

**Comment by alecritson** [comment]
> > I think it would be more beneficial if the media definition worked with extended models. My thinking is that you should be able to just remove model extending in one place without having to then update a bunch of config etc in order to remove it if that makes sense.
> 
> Totally agree. In config you prefer alias or fqcn?

I think alias should be sufficient since that's set up by Lunar so unlikely to cause issues and maybe less confusing for people using extending.

**Comment by wychoong** [comment]
> alias should be sufficient

done

**Review by glennjacobs — APPROVED** [review]

**Pull request merged**
