### PR TITLE
Dutch hub translations

### PR DESCRIPTION
**Pull request by timmydhooghe**
Adding Dutch lang files for the admin hub, as [discussed here](https://github.com/lunarphp/lunar/discussions/55).

### Progress:
- [x] account.php
- [x] auth.php
- [x] catalogue.php
- [x] components.php `Changed EN`
- [x] fieldtypes.php `Changed EN`
- [x] global.php
- [x] inputs.php
- [x] licensing.php
- [x] menu.php
- [x] notifications.php `Changed EN`
- [x] orders.php
- [x] partials.php `Changed EN`
- [x] settings.php
- [x] tables.php
- [x] validation.php

### QA:
- [ ] Browse the hub, find & fix any strange language given the context.
- [ ] Check length of translations in their context. Shorten if necessary.

### CODE REVIEW

**Comment by glennjacobs** [comment]
@timmydhooghe is this still an active PR?

**Comment by timmydhooghe** [comment]
> @timmydhooghe is this still an active PR?

@glennjacobs Normally, this would've been ready to merge by now, but I'm struggling with my health at the moment, hence the delay. Sorry about that.

All translations are done, so it's a matter of QA. If anyone would be able to go through it in the UI, and make some TODO comments in the language files if the lenght of the strings is way off, I can pick these up and finalise the translations.

**Comment by glennjacobs** [comment]
> > @timmydhooghe is this still an active PR?
> 
> @glennjacobs Normally, this would've been ready to merge by now, but I'm struggling with my health at the moment, hence the delay. Sorry about that.
> 
> All translations are done, so it's a matter of QA. If anyone would be able to go through it in the UI, and make some TODO comments in the language files if the lenght of the strings is way off, I can pick these up and finalise the translations.

Sorry to hear that, get well soon.

Unfortunately, I can't offer much help as I don't speak Dutch. I'll leave the PR open for now.

**Comment by glennjacobs** [comment]
@timmydhooghe are you going to be completing this PR? Thanks

**Comment by glennjacobs** [comment]
Closing as this PR has had a status of "Draft" for a long time and our focus is now moving to 1.x.

**Pull request closed without merging**
