### PR TITLE
Fix validation of attributes of type TranslatedText

### PR DESCRIPTION
**Pull request by fakeheal**
Applying additional validation rules (specified when adding/updating an attribute) to attributes of type `TranslatedText` is wrong. It is applying the rule to the field that is [a collection of items](https://github.com/lunarphp/lunar/blob/main/packages/core/src/FieldTypes/TranslatedText.php#L59). So if the rule `string` was added to the attribute it would validate the collection/array of items against it and **always** fail.

**Note**: If you're testing it and your attribute has the `RichText` feature enabled and is also required, the js plugin used for [WYSIWYG adds `<p><br></p>`](https://github.com/quilljs/quill/issues/1235) as content even when all the text is deleted and it looks like the required rule isn't working.

### CODE REVIEW

**Comment by alecritson** [comment]
Thanks for this @fakeheal . I'd be good to see a small test to ensure this is kicking in as expected.

**Comment by fakeheal** [comment]
@alecritson Sure! Is there a guide or something for starting up the existing tests or/and any guidelines?

**Comment by alecritson** [comment]
> @alecritson Sure! Is there a guide or something for starting up the existing tests or/and any guidelines?

We have some tests already in place i.e. https://github.com/lunarphp/lunar/blob/main/packages/admin/tests/Unit/Http/Livewire/Components/Products/ProductCreateTest.php#L89 so you can use these as a base if that helps. 

Also on Livewire's site there is some helpers for testing https://laravel-livewire.com/docs/2.x/testing#introduction

If you're unsure or get stuck let us know and we can help

**Comment by fakeheal** [comment]
@alecritson Thanks for the links. 

I just cloned my fork, ran `composer install` and then (using php8.1) ran `phpunit` (with `--filter` to "target" `ProductCreateTest`). Hope that's the correct way!

I added some test cases to the existing file testing mix of `FieldType`s that are required/optional + additional rules.

**Review by alecritson — APPROVED** [review]

**Comment by alecritson** [comment]
Thanks for this @fakeheal We're just finalising the sign off then we'll get this merged!

**Review by glennjacobs — APPROVED** [review]

**Pull request merged**
