### PR TITLE
Allow hub to be disabled

### PR DESCRIPTION
**Pull request by ryanmitchell**
In some system setups the hub would not be available on the same URL as the shopfront, for example when its a white-labelled store front. However it is still necessary to include the hub composer requirement as add-ons extend it (adding views, slots, components etc) as well as providing front end functionality.

In this situation it would be useful to be able to stop the hub displaying by not letting it respond on any routes.

This PR adds a `lunar-hub.system.enable` config setting, that when set to `false` does not enable any hub routes.

### CODE REVIEW

**Comment by ryanmitchell** [comment]
Got to love how pint highlights files that havent been changed by the PR 😕

**Comment by wychoong** [comment]
> Got to love how pint highlights files that havent been changed by the PR 😕

Glenn updated the pint to use the `--dirty` flag in main branch. but tbh i did like pint just fix and commit the changes

**Comment by alecritson** [comment]
Thanks @ryanmitchell is there any reason we couldn't add this logic to the service provider? i.e. https://github.com/lunarphp/lunar/blob/0.4/packages/admin/src/AdminHubServiceProvider.php#L203

**Comment by ryanmitchell** [comment]
Nope, no reason not to do it there. I'll update later.

**Comment by glennjacobs** [comment]
@ryanmitchell as this isn't a bug fix, can you please target `main`?

**Comment by ryanmitchell** [comment]
Yeah no problem. Thats updated.

**Review by glennjacobs — APPROVED** [review]

**Pull request merged**
