### PR TITLE
Add french language

### PR DESCRIPTION
**Pull request by StephaneBour**
Hello,

As for version 0.7 (https://github.com/lunarphp/lunar/pull/1489), here are the French translation files for the admin part.

### CODE REVIEW

**Comment by glennjacobs** [comment]
Thanks. But as we're still in alpha and so much can potentially change, I'm not going to merge this until we're closer to a stable release.

**Comment by StephaneBour** [comment]
No worries, I will adapt just before the release.

**Comment by glennjacobs** [comment]
> No worries, I will adapt just before the release.

I'll change to draft for the moment and once we hit beta we can come back to it.

**Comment by StephaneBour** [comment]
@glennjacobs I updated from 1.0-beta1

**Comment by glennjacobs** [comment]
@StephaneBour many thanks for this. I can see there's some updates for other languages. Can we ensure this PR is only for French? Also, could you give it a final check considering some bits may have changed and then we'll get it merged in.

**Comment by StephaneBour** [comment]
@glennjacobs this commit is a missing translation in English : https://github.com/lunarphp/lunar/pull/1630/commits/56ebfc950396210813d33f06c41ab7df0fa6cdb3

I check now if all translation are ok in French.

**Comment by StephaneBour** [comment]
It's ok, all keys in en are in fr 👍🏻

**Review by glennjacobs — APPROVED** [review]

**Comment by glennjacobs** [comment]
Many thanks @StephaneBour

**Pull request merged**
