### PR TITLE
Feature - Field translated text

### PR DESCRIPTION
**Pull request by lguichard**
This PR fix definitely the TranslatedText component for the MVP.  

It's a same UX approach that legacy version.  Let's get a simple solution working and consider a better solution later.

The issue related to #1425

### CODE REVIEW

**Comment by alecritson** [comment]
Thanks @lguichard I just ran into this when trying to edit a product

image

**Comment by lguichard** [comment]
@alecritson Fixed

**Comment by alecritson** [comment]
@lguichard Seems like there are still issues when saving product information https://flareapp.io/share/omww8YGm

**Comment by glennjacobs** [comment]
@lguichard can you fix the conflicts and confirm whether this is now ready to review, as @alecritson mentioned there were some issues with the richtext editor?

**Comment by lguichard** [comment]
@glennjacobs Ok, i'll merge from 1.x soon. 

 I tried to reproduce many times, i can't trigger the bug on Rich Editor 😄 I suspect bug with SPA mode with Filament.

**Comment by lguichard** [comment]
@glennjacobs That's it !

**Pull request merged**
