### PR TITLE
Feat [0.3] - Storefront session

### PR DESCRIPTION
**Pull request by alecritson**
This PR looks to add a `StorefrontSession` helper for storefronts to set things like channels, customer groups and currencies. It can be expanded going forward but this is a start for the essentials.

### CODE REVIEW

**Comment by glennjacobs** [comment]
@alecritson if we have Storefront Session pulled out into a "Storefront" section, should we have the same for the Cart Session?

**Comment by glennjacobs** [comment]
@alecritson what happens if a Customer belongs to multiple Customer Groups?

**Comment by alecritson** [comment]
> @alecritson if we have Storefront Session pulled out into a "Storefront" section, should we have the same for the Cart Session?

Yeah can pull it out on a separate PR, was done this way because there wasn't a suitable place for this.

**Comment by alecritson** [comment]
> @alecritson what happens if a Customer belongs to multiple Customer Groups?

It should still match right, unless you wanted to specify multiple customer groups to make it really specific.

**Comment by alecritson** [comment]
> > > @alecritson what happens if a Customer belongs to multiple Customer Groups?
> > 
> > 
> > It should still match right, unless you wanted to specify multiple customer groups to make it really specific.
> 
> Just thinking, if a User is logged in and the associated Customer record belongs to multiple Customer Groups, do we not need to consider them all for our queries?

We can certainly update the methods so it handles multiple.

**Comment by glennjacobs** [comment]
@alecritson docs need updating to show setting multiple customer groups.

**Review by glennjacobs — APPROVED** [review]

**Pull request merged**
