### PR TITLE
Fix - Product variants widget saving

### PR DESCRIPTION
**Pull request by lguichard**
This PR fixes when product variants saving avoid to erase data of product options shared.

### CODE REVIEW

**Comment by alecritson** [comment]
@lguichard Not too sure on this one as we want to allow users to edit the product option values which are linked  to the product (not shared) without having to go through the settings screen.

**Comment by lguichard** [comment]
In this case, there are the conflict with data save in settings screen and product screen. We should fix production variants edition.

**Comment by alecritson** [comment]
> In this case, there are the conflict with data save in settings screen and product screen. We should fix production variants edition.

I don't think it's so much of a problem if, when editing through the settings screen, it's restricted, since you should mainly be editing non shared product options via the product.

**Comment by lguichard** [comment]
@alecritson Humm, i think w’re talking about the same thing. My initial commit fix the bevahiour below :

- if someone has save the shared product option with handle = color and name fr : couleur / en : color. If you generate new variants in edit product the handle and localize fields are erase with new data.

I agree with all anothers points.

**Comment by lguichard** [comment]
@alecritson My bad, i changed the condition, I just noticed that write a bad condition ^^

**Review by alecritson — APPROVED** [review]

**Pull request merged**
