### PR TITLE
Feature/exclude searchable attributes

### PR DESCRIPTION
**Pull request by dewebdesigns**
Added a new configuration field in the search.php file to exclude searchable attributes.

This makes it easy to exclude information you do not want included when indexing them.

I have also included a test, and updated the docs.

### CODE REVIEW

**Comment by glennjacobs** [comment]
@dewebdesigns you should be targeting the `main` branch for new features.

Also, I'm not sure config is the correct approach, but I agree there should be a well-documented way of changing the Scout indexing. One way is implementing your own model, which you can do already.

@alecritson do we want a specific way to update the scout indexing on models, or do we simply advise developers to extend the model?

**Comment by wychoong** [comment]
> @dewebdesigns you should be targeting the `main` branch for new features.
> 
> Also, I'm not sure config is the correct approach, but I agree there should be a well-documented way of changing the Scout indexing. One way is implementing your own model, which you can do already.
> 
> @alecritson do we want a specific way to update the scout indexing on models, or do we simply advise developers to extend the model?

I think unless we found a solid way for model extension, I would advise not to. 

For this case I would suggest to use the observer way https://docs.lunarphp.io/core/extending/search.html
But currently the api is only for one way adding https://github.com/lunarphp/lunar/blob/0.4/packages/core/src/Base/Traits/Searchable.php

So I would suggest a mutator approach where you can add or remove as per needed.

**Comment by glennjacobs** [comment]
I think that makes sense. Maybe we need remove and replace methods, or similar.

**Comment by dewebdesigns** [comment]
I can take down the PR if you are planning on going in a different direction. I would like to request the following change at least from this PR:

Change `getSearchableAttributes` from `protected` to `public` on `Lunar\Models\Order`

I can put up a different PR, or one of you guys can add it to one of your current features - doesn't matter to me.

**Comment by glennjacobs** [comment]
I think the direction @wychoong suggested is the best approach.

**Pull request closed without merging**
