### PR TITLE
Feature - Refactor order status action

### PR DESCRIPTION
**Pull request by alecritson**
The action to update an orders status and preview the related emails is quite convoluted and the result is what should be a fairly quick action to perform, ends up being a bit of a chore.

For this reason, this PR removes the wizard and preview approach in favour of a more streamlined form, until this can be revisited.

### CODE REVIEW

**Comment by glennjacobs** [comment]
@alecritson I think the Additional Content and Email should only show once at least one mailer has been selected.

**Comment by alecritson** [comment]
> @alecritson I think the Additional Content and Email should only show once at least one mailer has been selected.

Pushed some tweaks for this 🤞

**Comment by glennjacobs** [comment]
I feel like we should default this to checked, as otherwise it's an additional click for 99% of orders.

image

**Comment by alecritson** [comment]
> I feel like we should default this to checked, as otherwise it's an additional click for 99% of orders.
> 
> image

This should hopefully be sorted.

**Review by glennjacobs — APPROVED** [review]

**Pull request merged**
