### PR TITLE
[0.2] File upload field type

### PR DESCRIPTION
**Pull request by alecritson**

### CODE REVIEW

**Comment by glennjacobs** [comment]
image

Coming across this error on a fairly clean install.

**Comment by alecritson** [comment]
> image
> 
> Coming across this error on a fairly clean install.

Should be sorted

**Comment by glennjacobs** [comment]
Seems to work OK now, but unsure about some bits.

image
The button to upload is quite separate to that of the label. Feels odd.

I see the uploader is almost like an asset manager. But will this not get overloaded with files over time?

**Comment by glennjacobs** [comment]
E.g.

Adding lots of files pushes it off the page

image

**Comment by glennjacobs** [comment]
- Should users be able to delete a file?
    - If so, will it automatically dissociate from the product/model?
- Should we allow a file to be updated?
- The asset browser probably needs to paginate
- Defo will need the facility to search the files
- When searching/paginating, how will the file selection persist?

**Review by glennjacobs — APPROVED** [review]

**Pull request merged**
