### PR TITLE
RTL: app layout

### PR DESCRIPTION
**Pull request by mustafa-online**
I started to work on RTL layout improvments.
More fixes to come.

### CODE REVIEW

**Comment by alecritson** [comment]
I've had a quick look and it seems like there are still quite a lot of considerations needed for things such as form alignment and various other UI tweaks for example:

image


I'll set this PR to draft and when you're happy that it's stable enough for a review then set it to ready and we'll take a look :)

**Comment by mustafa-online** [comment]
Yes, I've only work on the app layout. this the main purpose on this PR. it's ready.

as I said on discord, I will work on other areas and components. but on a separate PR's.

**Comment by mustafa-online** [comment]
It will take a lot of work to make the hub fully RTL.

**Comment by mustafa-online** [comment]
@alecritson

**Comment by glennjacobs** [comment]
@mustafa-online if this PR is ready, can you mark it as "Ready for review"?

I understand this is just to cover the app layout. 

You may be aware we're looking to move to Filament v3 for the hub later in the year, so that may influence whether you wish to continue this RTL work or not, as it supports RTL via the locale.

**Comment by mustafa-online** [comment]
@glennjacobs , Woooow **Filament** Finally <3
I guess it's better to wait for the filament integration, as the RTL needs a lot of work.

**Pull request closed without merging**
