### PR TITLE
fix: generate unique slugs using random string if necessary

### PR DESCRIPTION
**Pull request by fakeheal**
**Issue:** Creating a products with the same name, produces equal default URLs.

**Solution**: If slug exists, append random 5 character string <sup>1</sup>.

**Example:**
1. **Product**: Test Product, **Slug**: _test-product_
2. **Product**: Test Product, **Slug**: _test-product-abcd_

1: Another approach is to append the number of models matching the url, eg: test-product, test-product-1, test-product-2, etc.

### CODE REVIEW

**Comment by glennjacobs** [comment]
Thanks @fakeheal 

Could we go with the other approach, using numbers? E.g. test-product, test-product-1, test-product-2, etc.

I feel like that would be a tidier approach and probably a bit more understandable. A random string might just serve to confuse.

**Review by glennjacobs — CHANGES_REQUESTED** [review]
Change to use a numbering system instead.

**Comment by fakeheal** [comment]
@glennjacobs Changed it to a numbering system (heavily inspired by [eloquent-sluggable](https://github.com/cviebrock/eloquent-sluggable)).

**Example:**
1. **Product**: Test Product, **Slug**: _test-product_
2. **Product**: Test Product, **Slug**: _test-product-2_
3. **Product**: Test Product, **Slug**: _test-product-3_

**Review by fakeheal — COMMENTED** [review]
Changed it to a numbering system (heavily inspired by [eloquent-sluggable](https://github.com/cviebrock/eloquent-sluggable)).

**Example:**
1. **Product**: Test Product, **Slug**: _test-product_
2. **Product**: Test Product, **Slug**: _test-product-2_
3. **Product**: Test Product, **Slug**: _test-product-3_

**Review by glennjacobs — APPROVED** [review]

**Pull request merged**
