### PR TITLE
Fixes #502 and #1267

### LINKED ISSUE #502: multiple currencies and disabled
- GetCandy version: 2.0-beta15

### Expected Behaviour:
when disable currency, it should be disabled and won't be required when filling product info

### Actual Behaviour:
validation fails when save product for disabled currency
image

### Steps To Reproduce:
- more than 1 currency
- disable 1 currency
- fill prices except disabled currency

@glennjacobs mentioned on discord this could be:
1. on intention to avoid missing prices when re-enable the currency
2. for controlling currencies on frontend

for 1. i think it's valid but also at the same time the same issue will happen for adding new currency to the store. for 2., maybe a clearer label needed

### PR DESCRIPTION
**Pull request by amitavroy**
This pull request tries to fix issue #502 and also the issue I have raised i.e. #1267 
The solution for #502 kind of worked for my problem as well to add a check of the active currencies when creating a new product.

### CODE REVIEW

**Comment by amitavroy** [comment]
Strange. 

I raised a properly documented issue. Went through other issues to see if there exist a solution
and based on that, raise a PR to solve the issue.

If you are closing the issue at least comment on why you feel this is not proper. I genuinely wanted to contribute and wanted to help solve that issue.

@glennjacobs

**Comment by glennjacobs** [comment]
> Strange. 
> 
> 
> 
> I raised a properly documented issue. Went through other issues to see if there exist a solution
> 
> and based on that, raise a PR to solve the issue.
> 
> 
> 
> If you are closing the issue at least comment on why you feel this is not proper. I genuinely wanted to contribute and wanted to help solve that issue.
> 
> 
> 
> @glennjacobs 

I have on your referenced issue quite comprehensively.

**Comment by amitavroy** [comment]
Yes, I understood your stand for my issue of #1267. So, for now I guess I will work with that solution.

However, the PR also sovles #502 

If you are solving that also with some other approach, then yes I would be fine.

**Comment by glennjacobs** [comment]
I will have to check that old issue, but I don't believe this is the solution.

**Pull request closed without merging**
