### PR TITLE
Fix - Fieldtypes Toggle

### PR DESCRIPTION
**Pull request by lguichard**
Fix hydration of fieldtypes Toggle

### CODE REVIEW

**Comment by glennjacobs** [comment]
@lguichard I tested this and although I can see there is an issue, this PR doesn't appear to fix it for me.

**Comment by lguichard** [comment]
This pr is related to : https://github.com/lunarphp/lunar/pull/1666

**Comment by alecritson** [comment]
@lguichard is this PR reliant on the PR you references in order to work?

**Comment by lguichard** [comment]
> @lguichard is this PR reliant on the PR you references in order to work?

Yes, i close this issue.

**Pull request closed without merging**
