### PR TITLE
Fix espace query on DatabaseEngine (#1355)

### PR DESCRIPTION
**Pull request by lguichard**
This PR fix issue #1355 

DatabaseEngine no longer espace query on SQL 

The engine execute query without quote and generate syntax error on database server

Before 

```
SELECT
  *
FROM
  `search_index`
WHERE
  `index` = "demostore_products"
  AND MATCH (`content`) against (email@* IN boolean mode)
``` 

After 

```
SELECT
  *
FROM
  `search_index`
WHERE
  `index` = "demostore_products"
  AND MATCH (`content`) against ('"email@*"' IN boolean mode)
```

### CODE REVIEW

**Comment by glennjacobs** [comment]
Do we need the extra inverted commas? I assumed Laravel would handle that.

E.g. would this work?

```php
fn ($query) => $query->whereFullText('content', '"'.$builder->query.'*"', ['mode' => 'boolean'])
```

**Comment by glennjacobs** [comment]
Also, could you add a test to show it working?

**Comment by lguichard** [comment]
> Do we need the extra inverted commas? I assumed Laravel would handle that.
> 
> E.g. would this work?
> 
> ```
> fn ($query) => $query->whereFullText('content', '"'.$builder->query.'*"', ['mode' => 'boolean'])
> ```

No, me too !  Laravel don't espace, i needed to do before inject on whereFullText.

``` php
fn ($query) => $query->whereFullText('content', '"'.$builder->query.'*"', ['mode' => 'boolean'])
```
Works fine too. More clean 

But i found a new error with "@email string => Syntax error or access violation: 1064 syntax error, unexpected FTS_TERM, expecting FTS_NUMB.  

I had make a quick fix, but the issue is also maybe a mysql injection security report when boolean mode is active on Laravel ? I'm not found any espace on Illuminate/Database/Query/Grammars/MySqlGrammar.php

The code works in any case. I think no user will use the + and - operators in their search 

``` php
fn ($query) => $query->whereFullText('content', '"'.$builder->query.'*"')
```

**Comment by lguichard** [comment]
@alecritson i closed accidentally this issue, oups

**Pull request closed without merging**
